# Generated by Django 6.0.2 on 2026-03-01 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_code_data",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Данные QR-кода"
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("employee", "Сотрудник"),
                            ("guest", "Гость"),
                            ("temporary", "Временный"),
                        ],
                        max_length=20,
                        verbose_name="Тип пропуска",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Организация"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Действует с"
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="Действует до")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pass_photos/",
                        verbose_name="Фото",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_code_scanned",
                    models.CharField(
                        max_length=100, verbose_name="Сканированный QR-код"
                    ),
                ),
                (
                    "access_result",
                    models.CharField(
                        choices=[
                            ("granted", "Разрешен"),
                            ("denied", "Запрещен"),
                            ("expired", "Просрочен"),
                        ],
                        max_length=20,
                        verbose_name="Результат",
                    ),
                ),
                (
                    "access_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время попытки"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                (
                    "pass_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="access_control.pass",
                        verbose_name="Пропуск",
                    ),
                ),
            ],
        ),
    ]
