# Generated by Django 6.0.2 on 2026-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pass",
            name="qr_code_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="qrcodes/",
                verbose_name="QR-код (изображение)",
            ),
        ),
        migrations.AlterField(
            model_name="pass",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/",
                verbose_name="Фото сотрудника",
            ),
        ),
    ]
